apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: xdudakm-hospital

namespace: xdudakm-hospital

resources:
  - prepare.kustomization.yaml
  - cd.kustomization.yaml
  - install.kustomization.yaml
  - git-repository.yaml
  - ambulance-ufe.image-repository.yaml
  - ambulance-ufe.image-policy.yaml
  - image-update-automation.yaml