apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: xdudakm-hospital
      app.kubernetes.io/name: xdudakm-ambulance-wl

namespace: xdudakm-hospital

resources:
  - cd.kustomization.yaml
  - install.kustomization.yaml
  - git-repository.yaml