apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xdudakm-hospital

labels:
  - pairs:
      app.kubernetes.io/part-of: xdudakm-hospital
      app.kubernetes.io/name: xdudakm-ambulance-wl
    includeSelectors: true
    includeTemplates: true

resources:
  - ../../../apps/xdudakm-ambulance-ufe


components:
  - ../../../components/version-release