apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xdudakm-ambulance-ufe-content
spec:
  microFrontend: xdudakm-ambulance-ufe
  element: xdudakm-ambulance-wl-app
  attributes:
    - name: base-path
      value: /xdudakm-ambulance-wl/
    - name: api-base
      value: http://localhost:30081/api
    - name: ambulance-id
      value: bobulova
  displayRules:
    - allOf:
        - context-name: main-content
        - path: "^(\\.?/)?xdudakm-ambulance-wl(/.*)?$"
